---
name: Infection
version: dev-build-1
main: DarkGoldKnight\infection\Main
api:
- 2.0.0
- 3.0.0
author: DarkGoldKnight
description: Minigame implemented from a Call Of Duty Infected Gamemode

commands:
    infection:
        permission: infection.command
Contact GitHub API Training Shop Blog About
© 2017 GitHub, Inc. Terms Privacy Security Status Help
